meh

diff --git a/scripts/hello1/Makefile b/scripts/hello1/Makefile
--- a/scripts/hello1/Makefile
+++ b/scripts/hello1/Makefile
@@ -2,6 +2,9 @@ EXE=$(shell ocamlc -config-var ext_exe)
 BINDIR=bin
 ifndef LAUNCHER
 export LAUNCHER=./BOING
+export SRC=hello.perl
+export INST=HELLO.PL
+export INSTOTHER=hello.pl
 endif
 
 all:
@@ -12,17 +15,18 @@ setup:
 	ocamlfind ocamlc -package fmt,unix -linkall -linkpkg BOING.ml -o BOING$(EXE)
 	./BOING true
 	mkdir -p $(BINDIR)
-	cp hello.pl $(BINDIR)/HELLO.PL
+	cp $(SRC) $(BINDIR)/$(INST)
 	cp BOING$(EXE) $(BINDIR)/BOING$(EXE)
 	ls -la . bin
 
 test:
 	@echo "==== START ===="
-	./hello.pl
-	HELLO.PL || echo "ERROR: cannot exec HELLO.PL (from bin)"
-	$(LAUNCHER) hello.pl || echo "EXPECTED: PATH does not contain . in $(LAUNCHER)" 
-	$(LAUNCHER) BOING true || echo "ERROR: launcher cannot exec $(LAUNCHER)"
-	$(LAUNCHER) HELLO.PL || echo "ERROR: $(LAUNCHER) cannot exec HELLO.PL (from bin)"
+	./$(SRC)
+	$(INST) || echo "ERROR: cannot exec $(INST) (from bin)"
+	$(LAUNCHER) BOING true || echo "ERROR: launcher cannot exec BOING"
+	$(LAUNCHER) $(SRC) || echo "EXPECTED: PATH does not contain . in $(LAUNCHER)" 
+	$(LAUNCHER) $(INST) || echo "ERROR: $(LAUNCHER) cannot exec $(INST) (from bin)"
+	$(LAUNCHER) $(INSTOTHER) || echo "EXPECTED: $(LAUNCHER) cannot exec $(INSTOTHER) (from bin)"
 
 clean:
 	rm -rf *.cm* *.exe BOING yadda* foobar $(BINDIR)
